version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - keycloak

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    command: ["start-dev"]

volumes:
  mongo_data:
